# Generated by Django 2.1.3 on 2018-11-27 18:06

from django.db import migrations


def create_system_groups_and_users(apps, schema_editor):
    User = apps.get_model('notes', 'User')
    Group = apps.get_model('auth', 'Group')

    moderator_group = Group.objects.create(name='moderator_group')
    user_group = Group.objects.create(name='user_group')

    moderator_01 = User.objects.create(username='moderator_01')
    moderator_02 = User.objects.create(username='moderator_02')

    user_01 = User.objects.create(username='user_01')
    user_02 = User.objects.create(username='user_02')
    user_03 = User.objects.create(username='user_03')

    user_01.groups.add(user_group)
    user_02.groups.add(user_group)
    user_03.groups.add(user_group)

    moderator_01.groups.add(moderator_group)
    moderator_02.groups.add(moderator_group)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181120_0510'),
    ]

    operations = [
        migrations.RunPython(create_system_groups_and_users)
    ]
